name = "telemedicina-saas"
main = "worker.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

routes = [
  { pattern = "telemedicina.hamstersoftware.com", custom_domain = true }
]

[assets]
directory = "out"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "medischedule-db"
database_id = "02aa8350-a3de-4ab5-ab08-1fa6b1d8bfe8"
migrations_dir = "migrations"

