name = "telemedicina-saas"
main = "worker.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "out"
binding = "ASSETS"

# Descomentar e ingresar el UUID generado en Cloudflare tras ejecutar: npx wrangler d1 create medischedule-db
# [[d1_databases]]
# binding = "DB"
# database_name = "medischedule-db"
# database_id = "<UUID-DE-TU-BASE-D1>"
# migrations_dir = "migrations"
